# GENERATED by stack-forge 0.2.0 — DO NOT HAND-EDIT.
# Source of record: security/apps/policy-app/access.yaml
# source sha256: c26c1f9aa16223e0
# Change the manifest and re-run the pipeline; edits here are overwritten.
identity_token "alicloud" {
  audience = ["alicloud.tfc.vinothkaruppusamy"]
}

# The infrastructure stack must apply before this one. Terraform Cloud resolves the
# ordering from this block; if the upstream apply fails, this stack does not plan.
# The source is org/project/stack — the project segment is required, and the
# upstream stack must live in that same project for the reference to resolve.
upstream_input "infra" {
  type   = "stack"
  source = "app.terraform.io/vinothkaruppusamy/bu1-nonprod/policy-app-infra"
}


deployment "dev" {
  inputs = {
    env               = "dev"
    region            = "ap-southeast-1"
    role_arn          = "acs:ram::5698578488787527:role/tfc-sec-dev"
    oidc_provider_arn = "acs:ram::5698578488787527:oidc-provider/hcp-terraform"
    identity_token    = identity_token.alicloud.jwt


    cluster_rrsa_issuer       = upstream_input.infra.dev_cluster_rrsa_issuer
    cluster_rrsa_provider_arn = upstream_input.infra.dev_cluster_rrsa_provider_arn
    bucket_arns               = upstream_input.infra.dev_bucket_arns

    common_tags = {
      app_id     = "policy-app"
      bu         = "bu1"
      env        = "dev"
      managed_by = "stack-forge"
    }
  }
}

