# GENERATED by stack-forge 0.2.0 — DO NOT HAND-EDIT.
# Source of record: infra/apps/claims-app/manifest.yaml
# source sha256: 32d2397c8d80a931
# Change the manifest and re-run the pipeline; edits here are overwritten.
required_providers {
  alicloud = {
    source  = "aliyun/alicloud"
    version = "~> 1.245"
  }
}

variable "env" { type = string }
variable "region" { type = string }
variable "vpc_id" { type = string }
variable "vswitch_ids" { type = list(string) }
variable "role_arn" { type = string }
variable "oidc_provider_arn" { type = string }
variable "identity_token" {
  type      = string
  ephemeral = true
}
variable "common_tags" { type = map(string) }

provider "alicloud" "this" {
  config {
    region = var.region
    assume_role_with_oidc {
      oidc_provider_arn = var.oidc_provider_arn
      role_arn          = var.role_arn
      oidc_token        = var.identity_token
    }
  }
}

component "claims_cluster" {
  source  = "../../../../modules/module-ack"
  inputs = {
    cluster_name         = "claims-cluster-${var.env}"
    worker_instance_type = "ecs.g6.large"
    worker_count         = 2
    namespaces           = ["claims-app"]
    vpc_id               = var.vpc_id
    vswitch_ids          = var.vswitch_ids
    enable_rrsa          = true
    tags                 = var.common_tags
  }
  providers = {
    alicloud = provider.alicloud.this
  }
}

component "claims_documents" {
  source  = "../../../../modules/module-oss"
  inputs = {
    bucket_name   = "claims-documents-${var.env}"
    storage_class = "Standard"
    versioning    = true
    prefixes      = ["incoming/", "reports/"]
    encryption    = "KMS"
    tags          = var.common_tags
  }
  providers = {
    alicloud = provider.alicloud.this
  }
}


# Stack-level outputs. These exist so the deployment file has something to publish:
# publish_output cannot reach into `component.*` directly, it can only forward a
# named output of a specific deployment.

output "cluster_rrsa_issuer" {
  description = "RRSA OIDC issuer URL, consumed by the security stack to bind service accounts"
  type        = string
  value       = component.claims_cluster.rrsa_oidc_issuer_url
}

output "cluster_rrsa_provider_arn" {
  description = "RRSA OIDC provider ARN, used in the RAM role trust policies"
  type        = string
  value       = component.claims_cluster.rrsa_provider_arn
}

output "bucket_arns" {
  description = "Bucket name -> ARN, the resources RAM policies may be scoped to"
  type        = map(string)
  value       = { "claims-documents" = component.claims_documents.bucket_arn }
}

