# GENERATED by stack-forge 0.2.0 — DO NOT HAND-EDIT.
# Source of record: infra/apps/claims-app/manifest.yaml
# source sha256: 32d2397c8d80a931
# Change the manifest and re-run the pipeline; edits here are overwritten.
identity_token "alicloud" {
  audience = ["alicloud.tfc.vinothkaruppusamy"]
}


deployment "dev" {
  inputs = {
    env               = "dev"
    region            = "ap-southeast-1"
    vpc_id            = "vpc-0000000000000000dev"
    vswitch_ids       = ["vsw-0jl00000000000000dev", "vsw-0jl00000000000001dev"]
    role_arn          = "acs:ram::5698578488787527:role/tfc-stacks-dev"
    oidc_provider_arn = "acs:ram::5698578488787527:oidc-provider/hcp-terraform"
    identity_token    = identity_token.alicloud.jwt
    common_tags = {
      app_id     = "claims-app"
      bu         = "bu1"
      env        = "dev"
      managed_by = "stack-forge"
    }
  }
}


# Consumed by the security stack as upstream_input — this is the declared dependency
# that replaces passing the cluster OIDC issuer between teams by hand.
#
# A published output belongs to one deployment, not to the stack as a whole, so the
# name carries the environment. Two environments publishing a bare "bucket_arns"
# would otherwise collide and the security stack could not tell them apart.

publish_output "dev_cluster_rrsa_issuer" {
  description = "RRSA OIDC issuer URL, consumed by the security stack to bind service accounts (dev)"
  value       = deployment.dev.cluster_rrsa_issuer
}

publish_output "dev_cluster_rrsa_provider_arn" {
  description = "RRSA OIDC provider ARN, used in the RAM role trust policies (dev)"
  value       = deployment.dev.cluster_rrsa_provider_arn
}

publish_output "dev_bucket_arns" {
  description = "Bucket name -> ARN, the resources RAM policies may be scoped to (dev)"
  value       = deployment.dev.bucket_arns
}

