# GENERATED by stack-forge 0.2.0 — DO NOT HAND-EDIT.
# Source of record: security/apps/claims-app/access.yaml
# source sha256: 553b7a79489a4ee5
# Change the manifest and re-run the pipeline; edits here are overwritten.
required_providers {
  alicloud = {
    source  = "aliyun/alicloud"
    version = "~> 1.245"
  }
}

variable "env" { type = string }
variable "region" { type = string }
variable "role_arn" { type = string }
variable "oidc_provider_arn" { type = string }
variable "identity_token" {
  type      = string
  ephemeral = true
}
variable "common_tags" { type = map(string) }

# Cross-stack inputs, produced by the infrastructure stack. Generated from the same
# list that drives its publish_output blocks, so the two lanes cannot drift apart.

variable "cluster_rrsa_issuer" { type = string }
variable "cluster_rrsa_provider_arn" { type = string }
variable "bucket_arns" { type = map(string) }

provider "alicloud" "this" {
  config {
    region = var.region
    assume_role_with_oidc {
      oidc_provider_arn = var.oidc_provider_arn
      role_arn          = var.role_arn
      oidc_token        = var.identity_token
    }
  }
}

# Workload identity (RRSA): claims-api -> claims-api in claims-app
component "claims_api" {
  source = "../../../../modules/module-ram"
  inputs = {
    role_name         = "claims-api-${var.env}"
    trust_type        = "oidc"
    oidc_provider_arn = var.cluster_rrsa_provider_arn
    oidc_issuer_url   = var.cluster_rrsa_issuer
    service_account   = "claims-app:claims-api"
    policy_name       = "claims-api-${var.env}-policy"
    policy_actions    = ["oss:GetObject", "oss:ListObjects", "oss:PutObject", "oss:DeleteObject"]
    policy_resources  = [
      "${var.bucket_arns["claims-documents"]}/incoming/*"
    ]
    tags = var.common_tags
  }
  providers = {
    alicloud = provider.alicloud.this
  }
}

# Human access: RAM group GRP-BU1-CLAIMS-READER
component "claims_reader" {
  source = "../../../../modules/module-ram"
  inputs = {
    group_name       = "GRP-BU1-CLAIMS-READER"
    trust_type       = "account"
    policy_name      = "claims-reader-${var.env}-policy"
    policy_actions   = ["oss:GetObject", "oss:ListObjects"]
    policy_resources = [
      "${var.bucket_arns["claims-documents"]}/reports/*"
    ]
    tags = var.common_tags
  }
  providers = {
    alicloud = provider.alicloud.this
  }
}
