#!/usr/bin/env python3
"""stack-forge — claim manifests to Terraform Stacks, split by ownership lane.

  infra/apps/<app>/manifest.yaml    -> infra/apps/<app>/stacks/      (CODEOWNERS: Platform Operations)
  security/apps/<app>/access.yaml   -> security/apps/<app>/stacks/   (CODEOWNERS: Security Assurance)

Commands:
  validate --app <name>    schema-validate both manifests, no output written
  render   --app <name>    validate then render both lanes
  plan-tfc --app <name>    print the Terraform Cloud stacks that provisioning will create

Deterministic and idempotent: same inputs always produce byte-identical output.
"""
import argparse
import hashlib
import json
import pathlib
import re
import shutil
import sys

import jsonschema
import yaml
from jinja2 import Environment, FileSystemLoader, StrictUndefined

ROOT = pathlib.Path(__file__).resolve().parents[1]
CATALOG = ROOT / "catalog"
TEMPLATES = ROOT / "templates"
PLATFORM = ROOT / "platform" / "environments.yaml"
# A Stack fetches its configuration straight from the repo and never runs an init
# that could resolve providers for itself, so the pinned Terraform version and the
# provider lock have to be committed next to the HCL. They are Platform Operations-owned and
# copied verbatim into both lanes rather than being rendered.
ASSETS = ROOT / "platform" / "assets"
STACK_ASSETS = (".terraform-version", ".terraform.lock.hcl")
VERSION = "0.2.0"

HEADER = ("# GENERATED by stack-forge {v} — DO NOT HAND-EDIT.\n"
          "# Source of record: {src}\n"
          "# source sha256: {digest}\n"
          "# Change the manifest and re-run the pipeline; edits here are overwritten.")


# ----------------------------------------------------------------- helpers
def sha(path: pathlib.Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()[:16]


def load_yaml(path: pathlib.Path) -> dict:
    if not path.exists():
        sys.exit(f"[stack-forge] not found: {path.relative_to(ROOT)}")
    return yaml.safe_load(path.read_text())


def tf_name(name: str) -> str:
    return re.sub(r"[^a-z0-9_]", "_", name.lower())


def catalog_schema(ref: str):
    f = CATALOG / "claim-schemas" / f"{ref}.json"
    return json.loads(f.read_text()) if f.exists() else None


def matrix():
    return yaml.safe_load((CATALOG / "template-matrix.yaml").read_text())["modules"]


def sizing(kind: str) -> dict:
    f = CATALOG / "sizing-maps" / f"{kind}.yaml"
    return yaml.safe_load(f.read_text()) if f.exists() else {}


def jinja():
    return Environment(loader=FileSystemLoader(str(TEMPLATES)),
                       undefined=StrictUndefined, keep_trailing_newline=True)


# ----------------------------------------------------------------- validation
def validate_manifest(manifest: dict) -> list:
    errs = []
    meta = manifest.get("metadata", {})
    for field in ("appId", "bu", "environments"):
        if field not in meta:
            errs.append(f"metadata.{field} is required")
    for i, comp in enumerate(manifest.get("components", [])):
        ref = comp.get("claimSchema", "")
        schema = catalog_schema(ref)
        if schema is None:
            errs.append(f"components[{i}]: unknown claimSchema '{ref}' — not published in the catalog")
            continue
        for e in jsonschema.Draft202012Validator(schema).iter_errors(comp):
            errs.append(f"components[{i}] ({ref}): {e.message}")
    return errs


def validate_access(access: dict, manifest: dict) -> list:
    """Access claims are validated against the ram schema AND against the infra
    manifest — you cannot grant access to a resource that was never requested."""
    errs = []
    schema = catalog_schema("ram/v1")
    declared = {c["name"] for c in manifest.get("components", [])}
    entries = ([("workloadIdentity", w) for w in access.get("workloadIdentity", [])] +
               [("userAccess", u) for u in access.get("userAccess", [])])
    if not entries:
        errs.append("access.yaml declares no workloadIdentity or userAccess entries")

    for kind, entry in entries:
        probe = {"type": "ram", "claimSchema": "ram/v1",
                 "name": entry.get("name", ""),
                 "identity_type": "workload" if kind == "workloadIdentity" else "group",
                 "level": entry.get("level", "")}
        for e in jsonschema.Draft202012Validator(schema).iter_errors(probe):
            errs.append(f"{kind} '{entry.get('name','?')}': {e.message}")
        resource = entry.get("resource")
        if resource and resource not in declared:
            errs.append(f"{kind} '{entry.get('name','?')}': grants access to '{resource}', "
                        f"which is not declared in manifest.yaml (declared: {sorted(declared)})")
        if kind == "workloadIdentity":
            for field in ("namespace", "serviceAccount"):
                if not entry.get(field):
                    errs.append(f"workloadIdentity '{entry.get('name','?')}': {field} is required")
        if kind == "userAccess" and not entry.get("group"):
            errs.append(f"userAccess '{entry.get('name','?')}': group is required")
    return errs


# ----------------------------------------------------------------- resolution
def resolve_component(comp: dict) -> dict:
    m = matrix()
    ctype = comp["type"]
    if ctype not in m:
        sys.exit(f"[stack-forge] no template-matrix entry for '{ctype}'")
    resolved = {}
    smap = sizing(ctype).get("sizes", {})
    if "size" in comp:
        if comp["size"] not in smap:
            sys.exit(f"[stack-forge] size '{comp['size']}' not in sizing map for {ctype}")
        resolved.update(smap[comp["size"]])
    return {"tf_name": tf_name(comp["name"]), "claim": comp, "resolved": resolved,
            "module_source": m[ctype]["module_source"], "template": m[ctype]["template"]}


def resolve_access(entry: dict, kind: str) -> dict:
    m = matrix()
    levels = sizing("ram").get("levels", {})
    level = entry.get("level", "read")
    if level not in levels:
        sys.exit(f"[stack-forge] access level '{level}' not defined in the ram sizing map")
    return {"tf_name": tf_name(entry["name"]), "claim": entry,
            "resolved": levels[level], "module_source": m["ram"]["module_source"],
            "kind": kind}


def copy_stack_assets(dest: pathlib.Path) -> None:
    for name in STACK_ASSETS:
        src = ASSETS / name
        if not src.exists():
            sys.exit(f"[stack-forge] missing platform asset: {src}")
        shutil.copyfile(src, dest / name)


def environments(manifest: dict) -> tuple:
    cfg = load_yaml(PLATFORM)
    wanted = manifest["metadata"]["environments"]
    missing = [e for e in wanted if e not in cfg["environments"]]
    if missing:
        sys.exit(f"[stack-forge] environments not defined by platform config: {missing}")
    return ([dict(name=e, **cfg["environments"][e]) for e in wanted], cfg)


# ----------------------------------------------------------------- rendering
def render(app: str) -> dict:
    infra_dir = ROOT / "infra" / "apps" / app
    sec_dir = ROOT / "security" / "apps" / app
    manifest_path, access_path = infra_dir / "manifest.yaml", sec_dir / "access.yaml"
    manifest, access = load_yaml(manifest_path), load_yaml(access_path)

    errs = validate_manifest(manifest) + validate_access(access, manifest)
    if errs:
        print("VALIDATION FAILED:")
        for e in errs:
            print("  -", e)
        sys.exit(1)

    envs, cfg = environments(manifest)
    meta = manifest["metadata"]
    j = jinja()
    infra_stack = f"{app}-infra"
    audience = cfg["identity_token_audience"]

    # upstream_input resolves only within a project, so a split here would produce
    # HCL that renders cleanly and then fails to resolve in Terraform Cloud.
    if cfg["projects"]["infra"] != cfg["projects"]["security"]:
        sys.exit("[stack-forge] the infra and security projects must be the same: "
                 "upstream_input cannot cross a Terraform Cloud project boundary")

    # ---- infra lane ----
    comps = [resolve_component(c) for c in manifest["components"]]
    parts = [j.get_template("_base/infra.providers.j2").render(
        header=HEADER.format(v=VERSION, src="infra/apps/%s/manifest.yaml" % app, digest=sha(manifest_path)))]
    for c in comps:
        parts.append(j.get_template(f"{c['template']}/component.j2").render(c=c))

    buckets = [c for c in comps if c["claim"]["type"] == "oss"]
    clusters = [c for c in comps if c["claim"]["type"] == "ack"]
    publish = []
    if clusters:
        publish += [
            {"name": "cluster_rrsa_issuer", "type": "string",
             "value": f"component.{clusters[0]['tf_name']}.rrsa_oidc_issuer_url",
             "description": "RRSA OIDC issuer URL, consumed by the security stack to bind service accounts"},
            {"name": "cluster_rrsa_provider_arn", "type": "string",
             "value": f"component.{clusters[0]['tf_name']}.rrsa_provider_arn",
             "description": "RRSA OIDC provider ARN, used in the RAM role trust policies"},
        ]
    if buckets:
        pairs = ", ".join(f'"{b["claim"]["name"]}" = component.{b["tf_name"]}.bucket_arn' for b in buckets)
        publish.append({"name": "bucket_arns", "type": "map(string)",
                        "value": "{ " + pairs + " }",
                        "description": "Bucket name -> ARN, the resources RAM policies may be scoped to"})

    parts.append(j.get_template("_base/infra.outputs.j2").render(publish=publish))

    infra_out = infra_dir / "stacks"
    infra_out.mkdir(parents=True, exist_ok=True)
    (infra_out / "components.tfcomponent.hcl").write_text("\n".join(parts))
    (infra_out / "deployments.tfdeploy.hcl").write_text(
        j.get_template("_base/infra.deployments.j2").render(
            header=HEADER.format(v=VERSION, src="infra/apps/%s/manifest.yaml" % app, digest=sha(manifest_path)),
            envs=envs, meta=meta, publish=publish, audience=audience))
    copy_stack_assets(infra_out)

    # ---- security lane ----
    sec_items = ([resolve_access(w, "workload") for w in access.get("workloadIdentity", [])] +
                 [resolve_access(u, "group") for u in access.get("userAccess", [])])
    sparts = [j.get_template("_base/security.providers.j2").render(
        header=HEADER.format(v=VERSION, src="security/apps/%s/access.yaml" % app, digest=sha(access_path)),
        publish=publish)]
    for item in sec_items:
        tpl = "ram/v1/workload.j2" if item["kind"] == "workload" else "ram/v1/group.j2"
        sparts.append(j.get_template(tpl).render(c=item))

    sec_out = sec_dir / "stacks"
    sec_out.mkdir(parents=True, exist_ok=True)
    (sec_out / "components.tfcomponent.hcl").write_text("\n".join(sparts))
    (sec_out / "deployments.tfdeploy.hcl").write_text(
        j.get_template("_base/security.deployments.j2").render(
            header=HEADER.format(v=VERSION, src="security/apps/%s/access.yaml" % app, digest=sha(access_path)),
            envs=envs, meta=meta, tfc_org=cfg["tfc_org"], infra_stack=infra_stack,
            project=cfg["projects"]["infra"], audience=audience, publish=publish))
    copy_stack_assets(sec_out)

    return {"app": app, "infra_components": len(comps), "security_components": len(sec_items),
            "environments": [e["name"] for e in envs], "published_outputs": [p["name"] for p in publish],
            "projects": cfg["projects"]}


def main():
    ap = argparse.ArgumentParser(prog="stack-forge")
    sub = ap.add_subparsers(dest="cmd", required=True)
    for cmd in ("validate", "render", "plan-tfc"):
        sp = sub.add_parser(cmd)
        sp.add_argument("--app", required=True)
    a = ap.parse_args()

    if a.cmd == "validate":
        manifest = load_yaml(ROOT / "infra" / "apps" / a.app / "manifest.yaml")
        access = load_yaml(ROOT / "security" / "apps" / a.app / "access.yaml")
        errs = validate_manifest(manifest) + validate_access(access, manifest)
        if errs:
            print("VALIDATION FAILED:")
            for e in errs:
                print("  -", e)
            sys.exit(1)
        print(f"OK: {a.app} — {len(manifest['components'])} infra components, "
              f"{len(access.get('workloadIdentity', [])) + len(access.get('userAccess', []))} access entries")
    elif a.cmd == "render":
        r = render(a.app)
        print(f"rendered {r['app']}:")
        print(f"  infra/apps/{r['app']}/stacks/     {r['infra_components']} components, "
              f"deployments: {r['environments']}")
        print(f"  security/apps/{r['app']}/stacks/  {r['security_components']} components, "
              f"consuming: {r['published_outputs']}")
    else:
        r = render(a.app)
        print(json.dumps({
            "stacks": [
                {"name": f"{r['app']}-infra", "project": r["projects"]["infra"],
                 "directory": f"infra/apps/{r['app']}/stacks", "depends_on": None},
                {"name": f"{r['app']}-security", "project": r["projects"]["security"],
                 "directory": f"security/apps/{r['app']}/stacks",
                 "depends_on": f"{r['app']}-infra"},
            ]}, indent=2))


if __name__ == "__main__":
    main()
