#!/usr/bin/env python3
"""Publish claim schemas: parse each module's variables.tf (the full internal surface),
merge the Service Governance-owned claim-schema.yaml overlay, emit JSON Schema into the catalog.

Run:  python tools/build_claim_schemas.py
This is what a module-repo release pipeline would run on tag in the real org.
"""
import json
import pathlib
import sys

import hcl2
import yaml

ROOT = pathlib.Path(__file__).resolve().parents[1]
MODULES = ROOT / "modules"
OUT = ROOT / "catalog" / "claim-schemas"

JSON_TYPES = {"string": "string", "bool": "boolean", "number": "number",
              "array": "array", "boolean": "boolean", "object": "object"}


def module_variables(mod: pathlib.Path) -> dict:
    """Every variable the module actually declares — the internal surface."""
    out = {}
    with open(mod / "variables.tf") as f:
        for block in hcl2.load(f).get("variable", []):
            for name, body in block.items():
                out[name.strip('"')] = {
                    "description": str(body.get("description", "")).strip('"'),
                    "has_default": "default" in body,
                }
    return out


def sizing_table(module_name: str, group: str) -> dict:
    """The platform-owned lookup a virtual field resolves through."""
    path = ROOT / "catalog" / "sizing-maps" / f"{module_name}.yaml"
    if not path.exists():
        sys.exit(f"ERROR [{module_name}]: enum_from_sizing needs {path}, which is missing")
    table = (yaml.safe_load(path.read_text()) or {}).get(group)
    if not table:
        sys.exit(f"ERROR [{module_name}]: sizing map has no '{group}' group to draw an enum from")
    return table


def build(mod: pathlib.Path):
    overlay = yaml.safe_load((mod / "claim-schema.yaml").read_text())
    variables = module_variables(mod)
    props, required = {}, []

    for field, spec in overlay["exposed"].items():
        target = spec.get("maps_to", field)
        if not spec.get("virtual") and target not in variables:
            sys.exit(f"ERROR [{mod.name}]: exposed field '{field}' maps to "
                     f"'{target}' which is not declared in variables.tf")
        prop = {"type": JSON_TYPES.get(spec.get("type", "string"), "string")}
        for key in ("enum", "pattern", "default", "description"):
            if key in spec:
                prop[key] = spec[key]

        # Fields that resolve through a platform lookup take their allowed values
        # from that lookup rather than restating them. Restating drifts: a size
        # added to the sizing map but not to the overlay is silently unusable, and
        # one removed from the map but left in the overlay validates and then fails
        # at render. Publishing what each choice resolves to is deliberate — a BU
        # picking "small" should be able to see it means two ecs.g6.large nodes.
        if "enum_from_sizing" in spec:
            table = sizing_table(overlay["module"], spec["enum_from_sizing"])
            prop["enum"] = sorted(table)
            prop["x-resolves-to"] = {k: table[k] for k in sorted(table)}
        if spec.get("virtual"):
            prop["x-virtual"] = True
        if spec.get("maps_to"):
            prop["x-maps-to"] = spec["maps_to"]
        props[field] = prop
        if spec.get("required"):
            required.append(field)

    mod_name, ver = overlay["module"], overlay["claim_version"]
    schema = {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": f"claim-schemas/{mod_name}/{ver}.json",
        "title": f"{mod_name} claim ({ver})",
        "type": "object",
        "properties": {
            "type": {"const": mod_name},
            "claimSchema": {"const": f"{mod_name}/{ver}"},
            **props,
        },
        "required": ["type", "claimSchema", *required],
        "additionalProperties": False,
        "x-module": {
            "name": mod_name,
            "internal_variables": len(variables),
            "exposed_fields": len(props),
        },
    }
    return mod_name, ver, schema


def render_catalog_md(index: dict) -> str:
    """The page a business unit reads before writing a claim.

    Generated, never hand-written: a catalogue that can drift from the schemas it
    describes is worse than no catalogue, because people trust it.
    """
    out = ["# Service catalog — what a business unit may claim", "",
           "GENERATED by `tools/build_claim_schemas.py`. Do not edit by hand.", "",
           "Every field below is one a claim manifest may set. Anything not listed is",
           "owned by the platform and will be rejected by validation.", ""]
    for claim in index["claims"]:
        out += [f"## `{claim['type']}` — `claimSchema: {claim['claimSchema']}`", "",
                f"Module version pin: `{claim['module_version']}`", "",
                "| Field | Type | Required | Allowed values | Description |",
                "|---|---|---|---|---|"]
        for name, f in claim["fields"].items():
            allowed = ", ".join(f"`{v}`" for v in f["enum"]) if "enum" in f else (
                f"pattern `{f['pattern']}`" if "pattern" in f else "—")
            default = f" Default `{json.dumps(f['default'])}`." if "default" in f else ""
            desc = " ".join(str(f.get("description", "")).split()) + default
            out.append(f"| `{name}` | {f['type']} | {'yes' if f['required'] else 'no'} "
                       f"| {allowed} | {desc} |")
        out.append("")
        resolved = {n: f["resolves-to"] for n, f in claim["fields"].items() if "resolves-to" in f}
        for name, table in resolved.items():
            out += [f"What `{name}` resolves to:", "", "| Value | Resolves to |", "|---|---|"]
            for key, val in table.items():
                out.append(f"| `{key}` | `{json.dumps(val)}` |")
            out.append("")
    return "\n".join(out)


def main():
    OUT.mkdir(parents=True, exist_ok=True)
    published = []
    for mod in sorted(MODULES.iterdir()):
        if not (mod / "claim-schema.yaml").exists():
            continue
        name, ver, schema = build(mod)
        dest = OUT / name
        dest.mkdir(parents=True, exist_ok=True)
        (dest / f"{ver}.json").write_text(json.dumps(schema, indent=2) + "\n")
        published.append((name, ver, schema["x-module"]["internal_variables"],
                          schema["x-module"]["exposed_fields"]))

    for name, ver, internal, exposed in published:
        print(f"  published {name}/{ver}: {internal} module variables -> {exposed} BU-settable fields")

    # Rebuild the BU-facing index. Field-level detail is carried here on purpose:
    # a list of field names answers "what may I set" but not "what may I set it to",
    # and a business unit that has to open three files to find out will guess instead.
    matrix = yaml.safe_load((ROOT / "catalog" / "template-matrix.yaml").read_text())["modules"]
    index = {"claims": []}
    for schema_file in sorted(OUT.glob("*/*.json")):
        s = json.loads(schema_file.read_text())
        mod = s["x-module"]["name"]
        fields = {}
        for name, prop in s["properties"].items():
            if name in ("type", "claimSchema"):
                continue
            entry = {"type": prop.get("type"), "required": name in s["required"]}
            for key in ("description", "enum", "pattern", "default", "x-resolves-to"):
                if key in prop:
                    entry[key.replace("x-", "")] = prop[key]
            fields[name] = entry
        index["claims"].append({
            "type": mod,
            "claimSchema": f"{mod}/{schema_file.stem}",
            "module_version": matrix.get(mod, {}).get("module_version"),
            "required": [r for r in s["required"] if r not in ("type", "claimSchema")],
            "optional": [p for p in s["properties"]
                         if p not in s["required"] and p not in ("type", "claimSchema")],
            "fields": fields,
        })
    (ROOT / "catalog" / "index.json").write_text(json.dumps(index, indent=2) + "\n")
    (ROOT / "catalog" / "CATALOG.md").write_text(render_catalog_md(index))
    print(f"  index rebuilt: {[c['claimSchema'] for c in index['claims']]}")
    print("  catalog/CATALOG.md rebuilt")


if __name__ == "__main__":
    main()
